#pragma once


enum class SCENE_TYPE { SCENE_1, SCENE_2, SCENE_3, SCENE_END };
enum class LAYER_TYPE { LAYER_CAM, LAYER_1, LAYER_BOSS, LAYER_NPC, LAYER_MAPOBJECT, LAYER_BUILDING, LAYER_LANDSCAPE, LAYER_FOLIAGE, LAYER_EFFECT, LAYER_UI, LAYER_END };

enum class CHANGLI { 
	AIR_ATTACK01, AIR_ATTACK02, AIR_ATTACK03, AIR_ATTACK04, AIR_ATTACK05, AIR_ATTACK_END, AIR_ATTACK_LOOP, AIR_ATTACK_START,
	ATTACK01, ATTACK02, ATTACK03, ATTACK04, ATTACK05, ATTACK_AIRBORNE, ATTACK_SLAM_END, ATTACK_SLAM_LOOP, ATTACK_SLAM_START, 
	ATTACK_ULTIMATE, ATTACK_BOOST, DAMAGED01, DAMAGED02, FALL_LOOP, JUMP, JUMP_SECOND_BACK, JUMP_SECOND_FRONT,
	LAND_HEAVY, LAND_LIGHT, RUN_BACK, RUN_FRONT, RUN_LEFT, RUN_LEFT_BACK, RUN_LEFT_FRONT, RUN_RIGHT, RUN_RIGHT_BACK, 
	RUN_RIGHT_FRONT, RUN_LSTOP, RUN_RSTOP, RUN_TURNBACK, SKILL_END, SKILL_LOOP, SKILL_START, SLIDE, SPRINT_DASH, 
	STAND_EXP01, STAND_EXP02, STAND_EXP03, STAND_EXP04, STAND_IDLE, STAND_CHANGE, TURN90, 
	WALK_BACK, WALK_FRONT, WALK_LEFT, WALK_LEFT_BACK, WALK_LEFT_FRONT, WALK_RIGHT, WALK_RIGHT_BACK, WALK_RIGHT_FRONT,
					};

enum class PLAYER_STATE {
	IDLE, WALK, RUNNING, DASH, ATTACK, LAND, BOOST, JUMP, FALLING, AIRATTACK, SLAM, SKILL, ULTIMATE, STATE_END
};

enum class MONSTER_KNIGHT	{ ATTACK01, ATTACK02, ATTACK03, ATTACK04, BATTLESTANCE, BEHIT_END, BEHIT_LEFT, BEHIT_LOOP, BEHIT_RIGHT, BEHIT_START, DEATH,
								STANDBY_END, STANDBY_LOOP, STANDBY_START, STANDUP, WAKEUP, WALK_BACK, WALK_FRONT, WALK_LEFT, WALK_RIGHT };

enum class MONSTER_VOID		{ ATTACK01, ATTACK02, ATTACK03, BATTLESTANCE, BEHIT_END, BEHIT_LOOP, BEHIT_START, BEHIT_LEFT, BEHIT_RIGHT, DEATH, STANDBY,
								WAKEUP, WALK_BACK, WALK_FRONT, WALK_LEFT, WALK_RIGHT };

enum class MONSTER_SCAR		{ ATTACK01, ATTACK02, ATTACK03, ATTACK04, ATTACK05, ATTACK06, ATTACK07, ATTACK08, ATTACK09, ATTACK10, ATTACK11, ATTACK12, ATTACK13,
								DEATH, GROGGY, STAND01, STAND02, STUNNING01, STUNNING02, STUNNING03, STUNNING04 };

enum class NODESTATE { SUCCESS, FAILURE, RUNNING };
enum class ATTACKSTATE { ONREADY, ONRUNNING, FINISHED };

enum class FLOWTYPE { LERP, EASEOUT, SMOOTHSTEP, LINEAR };

enum class FOVPROGRESS { FOV_IN, FOV_OUT, FOV_END };

enum class PLAY_TYPE { ONREADY, ONSTART, ONPROGRESS, FINISHED, PLAY_END };
enum class LOADING_STATE { ONREADY, ONLOADING, COMPLETE, LS_END };