#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine {

	enum class COMPONENT_TYPE {
		COMPONENT_TRANSFORM, COMPONENT_MODEL, COMPONENT_ANIMATOR, COMPONENT_TERRAIN, COMPONENT_BUFFER, COMPONENT_TEXTURE, COMPONENT_RECT_BUFFER,
		COMPONENT_NAVIGATION,COMPONENT_STATIC_SHADER, COMPONENT_DYNAMIC_SHADER, COMPONENT_TERRAIN_SHADER, COMPONENT_SKYSPHERE_SHADER, COMPONENT_UI_SHADER, 
		COMPONENT_COLLIDER, COMPONENT_CUBETEX, COMPONENT_MESHINSTANCE, COMPONENT_SCROLL, COMPONENT_EFFECT, COMPONENT_END
	};

	enum class RENDER_TYPE		{ RENDER_PRIORITY, RENDER_NONBLEND, RENDER_NONBLEND2, RENDER_NONLIGHT, RENDER_BLEND, RENDER_EFFECT, RENDER_UI, RENDER_END };

	enum class RENDER_TARGET	  { DIFFUSE, NORMAL, SHADE, DEPTH, SPECULAR, BRIGHTPASS, VERTICALBLUR, HORIZONTALBLUR, COMBINDED, DEFERRED, SHADOW, NONLIGHT, RT_END };
	enum class MULTIRENDER_TARGET { GAMEOBJECT, LIGHT, SHADE, RT_END };

	enum class ANIMATION_TYPE	{ ANIMATION, NON_ANIMATION, INSTANCED, END	};
	enum class ANIMATION_LOOP	{ PAUSED, PLAY_ONCE, PLAY_LOOP ,END		};
	enum class ANIMATION_STATE	{ ONREADY, ONRUNNING, FINISHED			};

	enum class COLLIDER_TYPE	{ COLLIDER_AABB, COLLIDER_OBB, COLLIDER_SPHERE, COLLIDER_END };

	enum class DIRECTION_TYPE	{ FORWARD, BACKWARD, RIGHT, LEFT, UP, DOWN			};
	enum class VECTOR_TYPE		{ VECTOR_RIGHT, VECTOR_UP, VECTOR_LOOK, VECTOR_POS	};

	enum class LANDSCAPE		{ MAPOBJ, BUILDING, LANDSCAPE, FOLIAGE, BOSS, TYPE_END };
	
	enum class UI_TYPE			{ NORMAL, BUTTON, SLIDER, FILTER, EXTRA, END };

	enum class NAVMESH_TYPE		{ NAVMESH_HORIZONTAL, NAVMESH_VERTICAL, NAVMESH_DIAGONAL, NAVMESH_BLOCK, NAVMESH_END };
	enum class NAVMESH_VERTEX	{ A	, B	, C	, VTX_END  };
	enum class NAVMESH_LINE		{ AB, BC, CA, LINE_END };

	enum class KEYBOARDKEYSTATE { KKS_DOWN, KKS_HOLD, KKS_UP, KKS_END };
	enum class MOUSEKEYSTATE	{ MKS_LB  , MKS_RB  , MKS_MB, MKS_END };
	enum class MOUSEMOVESTATE	{ MMS_X   , MMS_Y   , MMS_W , MMS_END };

	enum class THREAD_TYPE		{ MAIN_THREAD, SUB_THREAD, THREAD_END };

	enum class WINMODE			{ WMODE_FULL, END, WMODE_WIN };

	enum class JUMPSTATE		{ READY, JUMPING, FALLING, LAND };

	enum class LIGHT_TYPE		{ DIRECTIONAL, POINT, END };
	enum class DEFERRED_TYPE	{ DEBUG, DIRECTIONAL, POINT, COMBINED, BRIGHTPASS, BLUR, BLOOM, PUREBR,  END};
}
#endif // Engine_Enum_h__