// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBCHANNEL_FB_CHANNEL_H_
#define FLATBUFFERS_GENERATED_FBCHANNEL_FB_CHANNEL_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "CommonStruct_generated.h"

namespace FB_Channel {

struct PositionKeyFrame;

struct RotationKeyFrame;

struct ScaleKeyFrame;

struct Channel;
struct ChannelBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PositionKeyFrame FLATBUFFERS_FINAL_CLASS {
 private:
  FB_Utility::Vector3 Position_;
  float TimeStamp_;

 public:
  PositionKeyFrame()
      : Position_(),
        TimeStamp_(0) {
  }
  PositionKeyFrame(const FB_Utility::Vector3 &_Position, float _TimeStamp)
      : Position_(_Position),
        TimeStamp_(::flatbuffers::EndianScalar(_TimeStamp)) {
  }
  const FB_Utility::Vector3 &Position() const {
    return Position_;
  }
  float TimeStamp() const {
    return ::flatbuffers::EndianScalar(TimeStamp_);
  }
};
FLATBUFFERS_STRUCT_END(PositionKeyFrame, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) RotationKeyFrame FLATBUFFERS_FINAL_CLASS {
 private:
  FB_Utility::Vector4 Rotation_;
  float TimeStamp_;

 public:
  RotationKeyFrame()
      : Rotation_(),
        TimeStamp_(0) {
  }
  RotationKeyFrame(const FB_Utility::Vector4 &_Rotation, float _TimeStamp)
      : Rotation_(_Rotation),
        TimeStamp_(::flatbuffers::EndianScalar(_TimeStamp)) {
  }
  const FB_Utility::Vector4 &Rotation() const {
    return Rotation_;
  }
  float TimeStamp() const {
    return ::flatbuffers::EndianScalar(TimeStamp_);
  }
};
FLATBUFFERS_STRUCT_END(RotationKeyFrame, 20);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) ScaleKeyFrame FLATBUFFERS_FINAL_CLASS {
 private:
  FB_Utility::Vector3 Scale_;
  float TimeStamp_;

 public:
  ScaleKeyFrame()
      : Scale_(),
        TimeStamp_(0) {
  }
  ScaleKeyFrame(const FB_Utility::Vector3 &_Scale, float _TimeStamp)
      : Scale_(_Scale),
        TimeStamp_(::flatbuffers::EndianScalar(_TimeStamp)) {
  }
  const FB_Utility::Vector3 &Scale() const {
    return Scale_;
  }
  float TimeStamp() const {
    return ::flatbuffers::EndianScalar(TimeStamp_);
  }
};
FLATBUFFERS_STRUCT_END(ScaleKeyFrame, 16);

struct Channel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChannelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITIONKEYFRAMELIST = 4,
    VT_ROTATIONKEYFRAMELIST = 6,
    VT_SCALEKEYFRAMELIST = 8,
    VT_POSITIONKEYFRAMECOUNT = 10,
    VT_ROTATIONKEYFRAMECOUNT = 12,
    VT_SCALEKEYFRAMECOUNT = 14,
    VT_CHANNELBONEINDEX = 16
  };
  const ::flatbuffers::Vector<const FB_Channel::PositionKeyFrame *> *PositionKeyFrameList() const {
    return GetPointer<const ::flatbuffers::Vector<const FB_Channel::PositionKeyFrame *> *>(VT_POSITIONKEYFRAMELIST);
  }
  const ::flatbuffers::Vector<const FB_Channel::RotationKeyFrame *> *RotationKeyFrameList() const {
    return GetPointer<const ::flatbuffers::Vector<const FB_Channel::RotationKeyFrame *> *>(VT_ROTATIONKEYFRAMELIST);
  }
  const ::flatbuffers::Vector<const FB_Channel::ScaleKeyFrame *> *ScaleKeyFrameList() const {
    return GetPointer<const ::flatbuffers::Vector<const FB_Channel::ScaleKeyFrame *> *>(VT_SCALEKEYFRAMELIST);
  }
  uint32_t PositionKeyFrameCount() const {
    return GetField<uint32_t>(VT_POSITIONKEYFRAMECOUNT, 0);
  }
  uint32_t RotationKeyFrameCount() const {
    return GetField<uint32_t>(VT_ROTATIONKEYFRAMECOUNT, 0);
  }
  uint32_t ScaleKeyFrameCount() const {
    return GetField<uint32_t>(VT_SCALEKEYFRAMECOUNT, 0);
  }
  uint32_t ChannelBoneIndex() const {
    return GetField<uint32_t>(VT_CHANNELBONEINDEX, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITIONKEYFRAMELIST) &&
           verifier.VerifyVector(PositionKeyFrameList()) &&
           VerifyOffset(verifier, VT_ROTATIONKEYFRAMELIST) &&
           verifier.VerifyVector(RotationKeyFrameList()) &&
           VerifyOffset(verifier, VT_SCALEKEYFRAMELIST) &&
           verifier.VerifyVector(ScaleKeyFrameList()) &&
           VerifyField<uint32_t>(verifier, VT_POSITIONKEYFRAMECOUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_ROTATIONKEYFRAMECOUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_SCALEKEYFRAMECOUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_CHANNELBONEINDEX, 4) &&
           verifier.EndTable();
  }
};

struct ChannelBuilder {
  typedef Channel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_PositionKeyFrameList(::flatbuffers::Offset<::flatbuffers::Vector<const FB_Channel::PositionKeyFrame *>> PositionKeyFrameList) {
    fbb_.AddOffset(Channel::VT_POSITIONKEYFRAMELIST, PositionKeyFrameList);
  }
  void add_RotationKeyFrameList(::flatbuffers::Offset<::flatbuffers::Vector<const FB_Channel::RotationKeyFrame *>> RotationKeyFrameList) {
    fbb_.AddOffset(Channel::VT_ROTATIONKEYFRAMELIST, RotationKeyFrameList);
  }
  void add_ScaleKeyFrameList(::flatbuffers::Offset<::flatbuffers::Vector<const FB_Channel::ScaleKeyFrame *>> ScaleKeyFrameList) {
    fbb_.AddOffset(Channel::VT_SCALEKEYFRAMELIST, ScaleKeyFrameList);
  }
  void add_PositionKeyFrameCount(uint32_t PositionKeyFrameCount) {
    fbb_.AddElement<uint32_t>(Channel::VT_POSITIONKEYFRAMECOUNT, PositionKeyFrameCount, 0);
  }
  void add_RotationKeyFrameCount(uint32_t RotationKeyFrameCount) {
    fbb_.AddElement<uint32_t>(Channel::VT_ROTATIONKEYFRAMECOUNT, RotationKeyFrameCount, 0);
  }
  void add_ScaleKeyFrameCount(uint32_t ScaleKeyFrameCount) {
    fbb_.AddElement<uint32_t>(Channel::VT_SCALEKEYFRAMECOUNT, ScaleKeyFrameCount, 0);
  }
  void add_ChannelBoneIndex(uint32_t ChannelBoneIndex) {
    fbb_.AddElement<uint32_t>(Channel::VT_CHANNELBONEINDEX, ChannelBoneIndex, 0);
  }
  explicit ChannelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Channel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Channel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Channel> CreateChannel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const FB_Channel::PositionKeyFrame *>> PositionKeyFrameList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const FB_Channel::RotationKeyFrame *>> RotationKeyFrameList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const FB_Channel::ScaleKeyFrame *>> ScaleKeyFrameList = 0,
    uint32_t PositionKeyFrameCount = 0,
    uint32_t RotationKeyFrameCount = 0,
    uint32_t ScaleKeyFrameCount = 0,
    uint32_t ChannelBoneIndex = 0) {
  ChannelBuilder builder_(_fbb);
  builder_.add_ChannelBoneIndex(ChannelBoneIndex);
  builder_.add_ScaleKeyFrameCount(ScaleKeyFrameCount);
  builder_.add_RotationKeyFrameCount(RotationKeyFrameCount);
  builder_.add_PositionKeyFrameCount(PositionKeyFrameCount);
  builder_.add_ScaleKeyFrameList(ScaleKeyFrameList);
  builder_.add_RotationKeyFrameList(RotationKeyFrameList);
  builder_.add_PositionKeyFrameList(PositionKeyFrameList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Channel> CreateChannelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<FB_Channel::PositionKeyFrame> *PositionKeyFrameList = nullptr,
    const std::vector<FB_Channel::RotationKeyFrame> *RotationKeyFrameList = nullptr,
    const std::vector<FB_Channel::ScaleKeyFrame> *ScaleKeyFrameList = nullptr,
    uint32_t PositionKeyFrameCount = 0,
    uint32_t RotationKeyFrameCount = 0,
    uint32_t ScaleKeyFrameCount = 0,
    uint32_t ChannelBoneIndex = 0) {
  auto PositionKeyFrameList__ = PositionKeyFrameList ? _fbb.CreateVectorOfStructs<FB_Channel::PositionKeyFrame>(*PositionKeyFrameList) : 0;
  auto RotationKeyFrameList__ = RotationKeyFrameList ? _fbb.CreateVectorOfStructs<FB_Channel::RotationKeyFrame>(*RotationKeyFrameList) : 0;
  auto ScaleKeyFrameList__ = ScaleKeyFrameList ? _fbb.CreateVectorOfStructs<FB_Channel::ScaleKeyFrame>(*ScaleKeyFrameList) : 0;
  return FB_Channel::CreateChannel(
      _fbb,
      PositionKeyFrameList__,
      RotationKeyFrameList__,
      ScaleKeyFrameList__,
      PositionKeyFrameCount,
      RotationKeyFrameCount,
      ScaleKeyFrameCount,
      ChannelBoneIndex);
}

inline const FB_Channel::Channel *GetChannel(const void *buf) {
  return ::flatbuffers::GetRoot<FB_Channel::Channel>(buf);
}

inline const FB_Channel::Channel *GetSizePrefixedChannel(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB_Channel::Channel>(buf);
}

template <bool B = false>
inline bool VerifyChannelBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB_Channel::Channel>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedChannelBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB_Channel::Channel>(nullptr);
}

inline void FinishChannelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Channel::Channel> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedChannelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Channel::Channel> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FB_Channel

#endif  // FLATBUFFERS_GENERATED_FBCHANNEL_FB_CHANNEL_H_
