// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBDYNAMICMESH_FB_DYNAMICMESH_H_
#define FLATBUFFERS_GENERATED_FBDYNAMICMESH_FB_DYNAMICMESH_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "CommonStruct_generated.h"

namespace FB_DynamicMesh {

struct DynamicMeshVertex;

struct DynamicMeshTexture;
struct DynamicMeshTextureBuilder;

struct DynamicMeshData;
struct DynamicMeshDataBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) DynamicMeshVertex FLATBUFFERS_FINAL_CLASS {
 private:
  FB_Utility::Vector3 Position_;
  FB_Utility::Vector3 Normal_;
  FB_Utility::Vector3 Tangent_;
  FB_Utility::Vector3 BiNormal_;
  FB_Utility::Vector2 TexCoord_;
  FB_Utility::Vector4 BoneIndex_;
  FB_Utility::Vector4 BoneWeight_;

 public:
  DynamicMeshVertex()
      : Position_(),
        Normal_(),
        Tangent_(),
        BiNormal_(),
        TexCoord_(),
        BoneIndex_(),
        BoneWeight_() {
  }
  DynamicMeshVertex(const FB_Utility::Vector3 &_Position, const FB_Utility::Vector3 &_Normal, const FB_Utility::Vector3 &_Tangent, const FB_Utility::Vector3 &_BiNormal, const FB_Utility::Vector2 &_TexCoord, const FB_Utility::Vector4 &_BoneIndex, const FB_Utility::Vector4 &_BoneWeight)
      : Position_(_Position),
        Normal_(_Normal),
        Tangent_(_Tangent),
        BiNormal_(_BiNormal),
        TexCoord_(_TexCoord),
        BoneIndex_(_BoneIndex),
        BoneWeight_(_BoneWeight) {
  }
  const FB_Utility::Vector3 &Position() const {
    return Position_;
  }
  const FB_Utility::Vector3 &Normal() const {
    return Normal_;
  }
  const FB_Utility::Vector3 &Tangent() const {
    return Tangent_;
  }
  const FB_Utility::Vector3 &BiNormal() const {
    return BiNormal_;
  }
  const FB_Utility::Vector2 &TexCoord() const {
    return TexCoord_;
  }
  const FB_Utility::Vector4 &BoneIndex() const {
    return BoneIndex_;
  }
  const FB_Utility::Vector4 &BoneWeight() const {
    return BoneWeight_;
  }
};
FLATBUFFERS_STRUCT_END(DynamicMeshVertex, 88);

struct DynamicMeshTexture FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DynamicMeshTextureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEXTURETYPE = 4,
    VT_TEXTUREFILEPATH = 6
  };
  uint32_t TextureType() const {
    return GetField<uint32_t>(VT_TEXTURETYPE, 0);
  }
  const ::flatbuffers::String *TextureFilePath() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXTUREFILEPATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TEXTURETYPE, 4) &&
           VerifyOffset(verifier, VT_TEXTUREFILEPATH) &&
           verifier.VerifyString(TextureFilePath()) &&
           verifier.EndTable();
  }
};

struct DynamicMeshTextureBuilder {
  typedef DynamicMeshTexture Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_TextureType(uint32_t TextureType) {
    fbb_.AddElement<uint32_t>(DynamicMeshTexture::VT_TEXTURETYPE, TextureType, 0);
  }
  void add_TextureFilePath(::flatbuffers::Offset<::flatbuffers::String> TextureFilePath) {
    fbb_.AddOffset(DynamicMeshTexture::VT_TEXTUREFILEPATH, TextureFilePath);
  }
  explicit DynamicMeshTextureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DynamicMeshTexture> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DynamicMeshTexture>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DynamicMeshTexture> CreateDynamicMeshTexture(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t TextureType = 0,
    ::flatbuffers::Offset<::flatbuffers::String> TextureFilePath = 0) {
  DynamicMeshTextureBuilder builder_(_fbb);
  builder_.add_TextureFilePath(TextureFilePath);
  builder_.add_TextureType(TextureType);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DynamicMeshTexture> CreateDynamicMeshTextureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t TextureType = 0,
    const char *TextureFilePath = nullptr) {
  auto TextureFilePath__ = TextureFilePath ? _fbb.CreateString(TextureFilePath) : 0;
  return FB_DynamicMesh::CreateDynamicMeshTexture(
      _fbb,
      TextureType,
      TextureFilePath__);
}

struct DynamicMeshData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DynamicMeshDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTEXLIST = 4,
    VT_INDEXLIST = 6,
    VT_TEXTURELIST = 8,
    VT_BONELOCALMATRIXLIST = 10,
    VT_BONEOFFSETMATRIXLIST = 12,
    VT_BONEINDEXLIST = 14
  };
  const ::flatbuffers::Vector<const FB_DynamicMesh::DynamicMeshVertex *> *VertexList() const {
    return GetPointer<const ::flatbuffers::Vector<const FB_DynamicMesh::DynamicMeshVertex *> *>(VT_VERTEXLIST);
  }
  const ::flatbuffers::Vector<uint32_t> *IndexList() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDEXLIST);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshTexture>> *TextureList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshTexture>> *>(VT_TEXTURELIST);
  }
  const ::flatbuffers::Vector<const FB_Utility::Matrix4x4 *> *BoneLocalMatrixList() const {
    return GetPointer<const ::flatbuffers::Vector<const FB_Utility::Matrix4x4 *> *>(VT_BONELOCALMATRIXLIST);
  }
  const ::flatbuffers::Vector<const FB_Utility::Matrix4x4 *> *BoneOffsetMatrixList() const {
    return GetPointer<const ::flatbuffers::Vector<const FB_Utility::Matrix4x4 *> *>(VT_BONEOFFSETMATRIXLIST);
  }
  const ::flatbuffers::Vector<uint32_t> *BoneIndexList() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_BONEINDEXLIST);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTEXLIST) &&
           verifier.VerifyVector(VertexList()) &&
           VerifyOffset(verifier, VT_INDEXLIST) &&
           verifier.VerifyVector(IndexList()) &&
           VerifyOffset(verifier, VT_TEXTURELIST) &&
           verifier.VerifyVector(TextureList()) &&
           verifier.VerifyVectorOfTables(TextureList()) &&
           VerifyOffset(verifier, VT_BONELOCALMATRIXLIST) &&
           verifier.VerifyVector(BoneLocalMatrixList()) &&
           VerifyOffset(verifier, VT_BONEOFFSETMATRIXLIST) &&
           verifier.VerifyVector(BoneOffsetMatrixList()) &&
           VerifyOffset(verifier, VT_BONEINDEXLIST) &&
           verifier.VerifyVector(BoneIndexList()) &&
           verifier.EndTable();
  }
};

struct DynamicMeshDataBuilder {
  typedef DynamicMeshData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_VertexList(::flatbuffers::Offset<::flatbuffers::Vector<const FB_DynamicMesh::DynamicMeshVertex *>> VertexList) {
    fbb_.AddOffset(DynamicMeshData::VT_VERTEXLIST, VertexList);
  }
  void add_IndexList(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> IndexList) {
    fbb_.AddOffset(DynamicMeshData::VT_INDEXLIST, IndexList);
  }
  void add_TextureList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshTexture>>> TextureList) {
    fbb_.AddOffset(DynamicMeshData::VT_TEXTURELIST, TextureList);
  }
  void add_BoneLocalMatrixList(::flatbuffers::Offset<::flatbuffers::Vector<const FB_Utility::Matrix4x4 *>> BoneLocalMatrixList) {
    fbb_.AddOffset(DynamicMeshData::VT_BONELOCALMATRIXLIST, BoneLocalMatrixList);
  }
  void add_BoneOffsetMatrixList(::flatbuffers::Offset<::flatbuffers::Vector<const FB_Utility::Matrix4x4 *>> BoneOffsetMatrixList) {
    fbb_.AddOffset(DynamicMeshData::VT_BONEOFFSETMATRIXLIST, BoneOffsetMatrixList);
  }
  void add_BoneIndexList(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> BoneIndexList) {
    fbb_.AddOffset(DynamicMeshData::VT_BONEINDEXLIST, BoneIndexList);
  }
  explicit DynamicMeshDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DynamicMeshData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DynamicMeshData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DynamicMeshData> CreateDynamicMeshData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const FB_DynamicMesh::DynamicMeshVertex *>> VertexList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> IndexList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshTexture>>> TextureList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const FB_Utility::Matrix4x4 *>> BoneLocalMatrixList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const FB_Utility::Matrix4x4 *>> BoneOffsetMatrixList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> BoneIndexList = 0) {
  DynamicMeshDataBuilder builder_(_fbb);
  builder_.add_BoneIndexList(BoneIndexList);
  builder_.add_BoneOffsetMatrixList(BoneOffsetMatrixList);
  builder_.add_BoneLocalMatrixList(BoneLocalMatrixList);
  builder_.add_TextureList(TextureList);
  builder_.add_IndexList(IndexList);
  builder_.add_VertexList(VertexList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DynamicMeshData> CreateDynamicMeshDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<FB_DynamicMesh::DynamicMeshVertex> *VertexList = nullptr,
    const std::vector<uint32_t> *IndexList = nullptr,
    const std::vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshTexture>> *TextureList = nullptr,
    const std::vector<FB_Utility::Matrix4x4> *BoneLocalMatrixList = nullptr,
    const std::vector<FB_Utility::Matrix4x4> *BoneOffsetMatrixList = nullptr,
    const std::vector<uint32_t> *BoneIndexList = nullptr) {
  auto VertexList__ = VertexList ? _fbb.CreateVectorOfStructs<FB_DynamicMesh::DynamicMeshVertex>(*VertexList) : 0;
  auto IndexList__ = IndexList ? _fbb.CreateVector<uint32_t>(*IndexList) : 0;
  auto TextureList__ = TextureList ? _fbb.CreateVector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshTexture>>(*TextureList) : 0;
  auto BoneLocalMatrixList__ = BoneLocalMatrixList ? _fbb.CreateVectorOfStructs<FB_Utility::Matrix4x4>(*BoneLocalMatrixList) : 0;
  auto BoneOffsetMatrixList__ = BoneOffsetMatrixList ? _fbb.CreateVectorOfStructs<FB_Utility::Matrix4x4>(*BoneOffsetMatrixList) : 0;
  auto BoneIndexList__ = BoneIndexList ? _fbb.CreateVector<uint32_t>(*BoneIndexList) : 0;
  return FB_DynamicMesh::CreateDynamicMeshData(
      _fbb,
      VertexList__,
      IndexList__,
      TextureList__,
      BoneLocalMatrixList__,
      BoneOffsetMatrixList__,
      BoneIndexList__);
}

inline const FB_DynamicMesh::DynamicMeshData *GetDynamicMeshData(const void *buf) {
  return ::flatbuffers::GetRoot<FB_DynamicMesh::DynamicMeshData>(buf);
}

inline const FB_DynamicMesh::DynamicMeshData *GetSizePrefixedDynamicMeshData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB_DynamicMesh::DynamicMeshData>(buf);
}

template <bool B = false>
inline bool VerifyDynamicMeshDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB_DynamicMesh::DynamicMeshData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedDynamicMeshDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB_DynamicMesh::DynamicMeshData>(nullptr);
}

inline void FinishDynamicMeshDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDynamicMeshDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FB_DynamicMesh

#endif  // FLATBUFFERS_GENERATED_FBDYNAMICMESH_FB_DYNAMICMESH_H_
