// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAPEDITOR_WORLDMAPDATA_H_
#define FLATBUFFERS_GENERATED_MAPEDITOR_WORLDMAPDATA_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace WorldMapData {

struct Vector3;

struct GameObject;
struct GameObjectBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 12);

struct GameObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GameObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_ROTATION = 6,
    VT_SCALE = 8
  };
  const WorldMapData::Vector3 *position() const {
    return GetStruct<const WorldMapData::Vector3 *>(VT_POSITION);
  }
  const WorldMapData::Vector3 *rotation() const {
    return GetStruct<const WorldMapData::Vector3 *>(VT_ROTATION);
  }
  const WorldMapData::Vector3 *scale() const {
    return GetStruct<const WorldMapData::Vector3 *>(VT_SCALE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<WorldMapData::Vector3>(verifier, VT_POSITION, 4) &&
           VerifyField<WorldMapData::Vector3>(verifier, VT_ROTATION, 4) &&
           VerifyField<WorldMapData::Vector3>(verifier, VT_SCALE, 4) &&
           verifier.EndTable();
  }
};

struct GameObjectBuilder {
  typedef GameObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(const WorldMapData::Vector3 *position) {
    fbb_.AddStruct(GameObject::VT_POSITION, position);
  }
  void add_rotation(const WorldMapData::Vector3 *rotation) {
    fbb_.AddStruct(GameObject::VT_ROTATION, rotation);
  }
  void add_scale(const WorldMapData::Vector3 *scale) {
    fbb_.AddStruct(GameObject::VT_SCALE, scale);
  }
  explicit GameObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GameObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GameObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GameObject> CreateGameObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const WorldMapData::Vector3 *position = nullptr,
    const WorldMapData::Vector3 *rotation = nullptr,
    const WorldMapData::Vector3 *scale = nullptr) {
  GameObjectBuilder builder_(_fbb);
  builder_.add_scale(scale);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  return builder_.Finish();
}

inline const WorldMapData::GameObject *GetGameObject(const void *buf) {
  return ::flatbuffers::GetRoot<WorldMapData::GameObject>(buf);
}

inline const WorldMapData::GameObject *GetSizePrefixedGameObject(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<WorldMapData::GameObject>(buf);
}

template <bool B = false>
inline bool VerifyGameObjectBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<WorldMapData::GameObject>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedGameObjectBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<WorldMapData::GameObject>(nullptr);
}

inline void FinishGameObjectBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<WorldMapData::GameObject> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGameObjectBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<WorldMapData::GameObject> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace WorldMapData

#endif  // FLATBUFFERS_GENERATED_MAPEDITOR_WORLDMAPDATA_H_
