// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STATICMESH_STATICMESH_H_
#define FLATBUFFERS_GENERATED_STATICMESH_STATICMESH_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace StaticMesh {

struct Vector3;

struct Vector2;

struct BoneData;

struct WeightData;

struct Vertex;

struct StaticMeshObject;
struct StaticMeshObjectBuilder;

struct MeshList;
struct MeshListBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vector2()
      : x_(0),
        y_(0) {
  }
  Vector2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vector2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) BoneData FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t BID1_;
  uint32_t BID2_;
  uint32_t BID3_;
  uint32_t BID4_;

 public:
  BoneData()
      : BID1_(0),
        BID2_(0),
        BID3_(0),
        BID4_(0) {
  }
  BoneData(uint32_t _BID1, uint32_t _BID2, uint32_t _BID3, uint32_t _BID4)
      : BID1_(::flatbuffers::EndianScalar(_BID1)),
        BID2_(::flatbuffers::EndianScalar(_BID2)),
        BID3_(::flatbuffers::EndianScalar(_BID3)),
        BID4_(::flatbuffers::EndianScalar(_BID4)) {
  }
  uint32_t BID1() const {
    return ::flatbuffers::EndianScalar(BID1_);
  }
  uint32_t BID2() const {
    return ::flatbuffers::EndianScalar(BID2_);
  }
  uint32_t BID3() const {
    return ::flatbuffers::EndianScalar(BID3_);
  }
  uint32_t BID4() const {
    return ::flatbuffers::EndianScalar(BID4_);
  }
};
FLATBUFFERS_STRUCT_END(BoneData, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) WeightData FLATBUFFERS_FINAL_CLASS {
 private:
  float WID1_;
  float WID2_;
  float WID3_;
  float WID4_;

 public:
  WeightData()
      : WID1_(0),
        WID2_(0),
        WID3_(0),
        WID4_(0) {
  }
  WeightData(float _WID1, float _WID2, float _WID3, float _WID4)
      : WID1_(::flatbuffers::EndianScalar(_WID1)),
        WID2_(::flatbuffers::EndianScalar(_WID2)),
        WID3_(::flatbuffers::EndianScalar(_WID3)),
        WID4_(::flatbuffers::EndianScalar(_WID4)) {
  }
  float WID1() const {
    return ::flatbuffers::EndianScalar(WID1_);
  }
  float WID2() const {
    return ::flatbuffers::EndianScalar(WID2_);
  }
  float WID3() const {
    return ::flatbuffers::EndianScalar(WID3_);
  }
  float WID4() const {
    return ::flatbuffers::EndianScalar(WID4_);
  }
};
FLATBUFFERS_STRUCT_END(WeightData, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vertex FLATBUFFERS_FINAL_CLASS {
 private:
  StaticMesh::Vector3 POS_;
  StaticMesh::Vector2 UV_;
  StaticMesh::Vector3 Normal_;
  StaticMesh::BoneData BoneID_;
  StaticMesh::WeightData Weight_;

 public:
  Vertex()
      : POS_(),
        UV_(),
        Normal_(),
        BoneID_(),
        Weight_() {
  }
  Vertex(const StaticMesh::Vector3 &_POS, const StaticMesh::Vector2 &_UV, const StaticMesh::Vector3 &_Normal, const StaticMesh::BoneData &_BoneID, const StaticMesh::WeightData &_Weight)
      : POS_(_POS),
        UV_(_UV),
        Normal_(_Normal),
        BoneID_(_BoneID),
        Weight_(_Weight) {
  }
  const StaticMesh::Vector3 &POS() const {
    return POS_;
  }
  const StaticMesh::Vector2 &UV() const {
    return UV_;
  }
  const StaticMesh::Vector3 &Normal() const {
    return Normal_;
  }
  const StaticMesh::BoneData &BoneID() const {
    return BoneID_;
  }
  const StaticMesh::WeightData &Weight() const {
    return Weight_;
  }
};
FLATBUFFERS_STRUCT_END(Vertex, 64);

struct StaticMeshObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StaticMeshObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTEXLIST = 4,
    VT_INDEXLIST = 6,
    VT_TEXTUREDATA = 8,
    VT_MAXCOORDVERTEX = 10,
    VT_MINCOORDVERTEX = 12
  };
  const ::flatbuffers::Vector<const StaticMesh::Vertex *> *VertexList() const {
    return GetPointer<const ::flatbuffers::Vector<const StaticMesh::Vertex *> *>(VT_VERTEXLIST);
  }
  const ::flatbuffers::Vector<uint32_t> *IndexList() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDEXLIST);
  }
  const ::flatbuffers::Vector<uint8_t> *TextureData() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_TEXTUREDATA);
  }
  const StaticMesh::Vector3 *MaxCoordVertex() const {
    return GetStruct<const StaticMesh::Vector3 *>(VT_MAXCOORDVERTEX);
  }
  const StaticMesh::Vector3 *MinCoordVertex() const {
    return GetStruct<const StaticMesh::Vector3 *>(VT_MINCOORDVERTEX);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTEXLIST) &&
           verifier.VerifyVector(VertexList()) &&
           VerifyOffset(verifier, VT_INDEXLIST) &&
           verifier.VerifyVector(IndexList()) &&
           VerifyOffset(verifier, VT_TEXTUREDATA) &&
           verifier.VerifyVector(TextureData()) &&
           VerifyField<StaticMesh::Vector3>(verifier, VT_MAXCOORDVERTEX, 4) &&
           VerifyField<StaticMesh::Vector3>(verifier, VT_MINCOORDVERTEX, 4) &&
           verifier.EndTable();
  }
};

struct StaticMeshObjectBuilder {
  typedef StaticMeshObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_VertexList(::flatbuffers::Offset<::flatbuffers::Vector<const StaticMesh::Vertex *>> VertexList) {
    fbb_.AddOffset(StaticMeshObject::VT_VERTEXLIST, VertexList);
  }
  void add_IndexList(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> IndexList) {
    fbb_.AddOffset(StaticMeshObject::VT_INDEXLIST, IndexList);
  }
  void add_TextureData(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> TextureData) {
    fbb_.AddOffset(StaticMeshObject::VT_TEXTUREDATA, TextureData);
  }
  void add_MaxCoordVertex(const StaticMesh::Vector3 *MaxCoordVertex) {
    fbb_.AddStruct(StaticMeshObject::VT_MAXCOORDVERTEX, MaxCoordVertex);
  }
  void add_MinCoordVertex(const StaticMesh::Vector3 *MinCoordVertex) {
    fbb_.AddStruct(StaticMeshObject::VT_MINCOORDVERTEX, MinCoordVertex);
  }
  explicit StaticMeshObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StaticMeshObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StaticMeshObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StaticMeshObject> CreateStaticMeshObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const StaticMesh::Vertex *>> VertexList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> IndexList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> TextureData = 0,
    const StaticMesh::Vector3 *MaxCoordVertex = nullptr,
    const StaticMesh::Vector3 *MinCoordVertex = nullptr) {
  StaticMeshObjectBuilder builder_(_fbb);
  builder_.add_MinCoordVertex(MinCoordVertex);
  builder_.add_MaxCoordVertex(MaxCoordVertex);
  builder_.add_TextureData(TextureData);
  builder_.add_IndexList(IndexList);
  builder_.add_VertexList(VertexList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StaticMeshObject> CreateStaticMeshObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<StaticMesh::Vertex> *VertexList = nullptr,
    const std::vector<uint32_t> *IndexList = nullptr,
    const std::vector<uint8_t> *TextureData = nullptr,
    const StaticMesh::Vector3 *MaxCoordVertex = nullptr,
    const StaticMesh::Vector3 *MinCoordVertex = nullptr) {
  auto VertexList__ = VertexList ? _fbb.CreateVectorOfStructs<StaticMesh::Vertex>(*VertexList) : 0;
  auto IndexList__ = IndexList ? _fbb.CreateVector<uint32_t>(*IndexList) : 0;
  auto TextureData__ = TextureData ? _fbb.CreateVector<uint8_t>(*TextureData) : 0;
  return StaticMesh::CreateStaticMeshObject(
      _fbb,
      VertexList__,
      IndexList__,
      TextureData__,
      MaxCoordVertex,
      MinCoordVertex);
}

struct MeshList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESHES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<StaticMesh::StaticMeshObject>> *Meshes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<StaticMesh::StaticMeshObject>> *>(VT_MESHES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MESHES) &&
           verifier.VerifyVector(Meshes()) &&
           verifier.VerifyVectorOfTables(Meshes()) &&
           verifier.EndTable();
  }
};

struct MeshListBuilder {
  typedef MeshList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Meshes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StaticMesh::StaticMeshObject>>> Meshes) {
    fbb_.AddOffset(MeshList::VT_MESHES, Meshes);
  }
  explicit MeshListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshList> CreateMeshList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<StaticMesh::StaticMeshObject>>> Meshes = 0) {
  MeshListBuilder builder_(_fbb);
  builder_.add_Meshes(Meshes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshList> CreateMeshListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<StaticMesh::StaticMeshObject>> *Meshes = nullptr) {
  auto Meshes__ = Meshes ? _fbb.CreateVector<::flatbuffers::Offset<StaticMesh::StaticMeshObject>>(*Meshes) : 0;
  return StaticMesh::CreateMeshList(
      _fbb,
      Meshes__);
}

inline const StaticMesh::MeshList *GetMeshList(const void *buf) {
  return ::flatbuffers::GetRoot<StaticMesh::MeshList>(buf);
}

inline const StaticMesh::MeshList *GetSizePrefixedMeshList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<StaticMesh::MeshList>(buf);
}

template <bool B = false>
inline bool VerifyMeshListBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<StaticMesh::MeshList>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMeshListBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<StaticMesh::MeshList>(nullptr);
}

inline void FinishMeshListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<StaticMesh::MeshList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMeshListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<StaticMesh::MeshList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace StaticMesh

#endif  // FLATBUFFERS_GENERATED_STATICMESH_STATICMESH_H_
