// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMONSTRUCT_UTILITY_H_
#define FLATBUFFERS_GENERATED_COMMONSTRUCT_UTILITY_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace FB_Utility {

struct Vector4;

struct Vector3;

struct Vector2;

struct Matrix4x4;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vector4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vector4(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vector4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vector2()
      : x_(0),
        y_(0) {
  }
  Vector2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vector2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Matrix4x4 FLATBUFFERS_FINAL_CLASS {
 private:
  float m_[16];

 public:
  Matrix4x4()
      : m_() {
  }
  Matrix4x4(XMFLOAT4X4 _MAT) {
      m_[0] = _MAT._11; m_[1] = _MAT._12; m_[2] = _MAT._13; m_[3] = _MAT._14;
      m_[4] = _MAT._21; m_[5] = _MAT._22; m_[6] = _MAT._23; m_[7] = _MAT._24;
      m_[8] = _MAT._31; m_[9] = _MAT._32; m_[10] = _MAT._33; m_[11] = _MAT._34;
      m_[12]= _MAT._41; m_[13] = _MAT._42; m_[14] = _MAT._43; m_[15] = _MAT._44;
  }
  void Copy(XMFLOAT4X4 *_MAT) {

      _MAT->_11 = m_[0]; _MAT->_12 = m_[1];_MAT->_13 = m_[2]; _MAT->_14 = m_[3];
      _MAT->_21 = m_[4]; _MAT->_22 = m_[5];_MAT->_23 = m_[6]; _MAT->_24 = m_[7];
      _MAT->_31 = m_[8]; _MAT->_32 = m_[9];_MAT->_33 = m_[10]; _MAT->_34 = m_[11];
      _MAT->_41 = m_[12]; _MAT->_42 = m_[13]; _MAT->_43 = m_[14]; _MAT->_44 = m_[15];
  }
  Matrix4x4(::flatbuffers::span<const float, 16> _m) {
    ::flatbuffers::CastToArray(m_).CopyFromSpan(_m);
  }
  const ::flatbuffers::Array<float, 16> *m() const {
    return &::flatbuffers::CastToArray(m_);
  }
};
FLATBUFFERS_STRUCT_END(Matrix4x4, 64);

}  // namespace FB_Utility

#endif  // FLATBUFFERS_GENERATED_COMMONSTRUCT_UTILITY_H_
