// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBANIMATION_FB_ANIMATION_H_
#define FLATBUFFERS_GENERATED_FBANIMATION_FB_ANIMATION_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "FB_Channel_generated.h"

namespace FB_Animation {

struct AnimationInfo;

struct Animation;
struct AnimationBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) AnimationInfo FLATBUFFERS_FINAL_CLASS {
 private:
  float Duration_;
  float TicksPerSecond_;

 public:
  AnimationInfo()
      : Duration_(0),
        TicksPerSecond_(0) {
  }
  AnimationInfo(float _Duration, float _TicksPerSecond)
      : Duration_(::flatbuffers::EndianScalar(_Duration)),
        TicksPerSecond_(::flatbuffers::EndianScalar(_TicksPerSecond)) {
  }
  float Duration() const {
    return ::flatbuffers::EndianScalar(Duration_);
  }
  float TicksPerSecond() const {
    return ::flatbuffers::EndianScalar(TicksPerSecond_);
  }
};
FLATBUFFERS_STRUCT_END(AnimationInfo, 8);

struct Animation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ANIMATIONDATA = 4,
    VT_ANIMATIONNAME = 6,
    VT_CHANNELLIST = 8
  };
  const FB_Animation::AnimationInfo *AnimationData() const {
    return GetStruct<const FB_Animation::AnimationInfo *>(VT_ANIMATIONDATA);
  }
  const ::flatbuffers::String *AnimationName() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ANIMATIONNAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FB_Channel::Channel>> *ChannelList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FB_Channel::Channel>> *>(VT_CHANNELLIST);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<FB_Animation::AnimationInfo>(verifier, VT_ANIMATIONDATA, 4) &&
           VerifyOffset(verifier, VT_ANIMATIONNAME) &&
           verifier.VerifyString(AnimationName()) &&
           VerifyOffset(verifier, VT_CHANNELLIST) &&
           verifier.VerifyVector(ChannelList()) &&
           verifier.VerifyVectorOfTables(ChannelList()) &&
           verifier.EndTable();
  }
};

struct AnimationBuilder {
  typedef Animation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_AnimationData(const FB_Animation::AnimationInfo *AnimationData) {
    fbb_.AddStruct(Animation::VT_ANIMATIONDATA, AnimationData);
  }
  void add_AnimationName(::flatbuffers::Offset<::flatbuffers::String> AnimationName) {
    fbb_.AddOffset(Animation::VT_ANIMATIONNAME, AnimationName);
  }
  void add_ChannelList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_Channel::Channel>>> ChannelList) {
    fbb_.AddOffset(Animation::VT_CHANNELLIST, ChannelList);
  }
  explicit AnimationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Animation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Animation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Animation> CreateAnimation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const FB_Animation::AnimationInfo *AnimationData = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> AnimationName = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_Channel::Channel>>> ChannelList = 0) {
  AnimationBuilder builder_(_fbb);
  builder_.add_ChannelList(ChannelList);
  builder_.add_AnimationName(AnimationName);
  builder_.add_AnimationData(AnimationData);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Animation> CreateAnimationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const FB_Animation::AnimationInfo *AnimationData = nullptr,
    const char *AnimationName = nullptr,
    const std::vector<::flatbuffers::Offset<FB_Channel::Channel>> *ChannelList = nullptr) {
  auto AnimationName__ = AnimationName ? _fbb.CreateString(AnimationName) : 0;
  auto ChannelList__ = ChannelList ? _fbb.CreateVector<::flatbuffers::Offset<FB_Channel::Channel>>(*ChannelList) : 0;
  return FB_Animation::CreateAnimation(
      _fbb,
      AnimationData,
      AnimationName__,
      ChannelList__);
}

inline const FB_Animation::Animation *GetAnimation(const void *buf) {
  return ::flatbuffers::GetRoot<FB_Animation::Animation>(buf);
}

inline const FB_Animation::Animation *GetSizePrefixedAnimation(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB_Animation::Animation>(buf);
}

template <bool B = false>
inline bool VerifyAnimationBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB_Animation::Animation>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedAnimationBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB_Animation::Animation>(nullptr);
}

inline void FinishAnimationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Animation::Animation> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAnimationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Animation::Animation> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FB_Animation

#endif  // FLATBUFFERS_GENERATED_FBANIMATION_FB_ANIMATION_H_
