// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBANIMATOR_FB_ANIMATOR_H_
#define FLATBUFFERS_GENERATED_FBANIMATOR_FB_ANIMATOR_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "CommonStruct_generated.h"
#include "FB_Animation_generated.h"

namespace FB_Animator {

struct Animator;
struct AnimatorBuilder;

struct Animator FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimatorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ANIMATIONLIST = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<FB_Animation::Animation>> *AnimationList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FB_Animation::Animation>> *>(VT_ANIMATIONLIST);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ANIMATIONLIST) &&
           verifier.VerifyVector(AnimationList()) &&
           verifier.VerifyVectorOfTables(AnimationList()) &&
           verifier.EndTable();
  }
};

struct AnimatorBuilder {
  typedef Animator Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_AnimationList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_Animation::Animation>>> AnimationList) {
    fbb_.AddOffset(Animator::VT_ANIMATIONLIST, AnimationList);
  }
  explicit AnimatorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Animator> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Animator>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Animator> CreateAnimator(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_Animation::Animation>>> AnimationList = 0) {
  AnimatorBuilder builder_(_fbb);
  builder_.add_AnimationList(AnimationList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Animator> CreateAnimatorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<FB_Animation::Animation>> *AnimationList = nullptr) {
  auto AnimationList__ = AnimationList ? _fbb.CreateVector<::flatbuffers::Offset<FB_Animation::Animation>>(*AnimationList) : 0;
  return FB_Animator::CreateAnimator(
      _fbb,
      AnimationList__);
}

inline const FB_Animator::Animator *GetAnimator(const void *buf) {
  return ::flatbuffers::GetRoot<FB_Animator::Animator>(buf);
}

inline const FB_Animator::Animator *GetSizePrefixedAnimator(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB_Animator::Animator>(buf);
}

template <bool B = false>
inline bool VerifyAnimatorBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB_Animator::Animator>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedAnimatorBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB_Animator::Animator>(nullptr);
}

inline void FinishAnimatorBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Animator::Animator> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAnimatorBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Animator::Animator> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FB_Animator

#endif  // FLATBUFFERS_GENERATED_FBANIMATOR_FB_ANIMATOR_H_
