// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBBONE_FB_BONE_H_
#define FLATBUFFERS_GENERATED_FBBONE_FB_BONE_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "CommonStruct_generated.h"

namespace FB_Bone {

struct BoneData;
struct BoneDataBuilder;

struct BoneData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoneDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOCALTRANSFORM = 4,
    VT_COMBINEDMATRIX = 6,
    VT_PARENTBONEINDEX = 8,
    VT_BONENAME = 10
  };
  const FB_Utility::Matrix4x4 *LocalTransform() const {
    return GetStruct<const FB_Utility::Matrix4x4 *>(VT_LOCALTRANSFORM);
  }
  const FB_Utility::Matrix4x4 *CombinedMatrix() const {
    return GetStruct<const FB_Utility::Matrix4x4 *>(VT_COMBINEDMATRIX);
  }
  int32_t ParentBoneIndex() const {
    return GetField<int32_t>(VT_PARENTBONEINDEX, 0);
  }
  const ::flatbuffers::String *BoneName() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BONENAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<FB_Utility::Matrix4x4>(verifier, VT_LOCALTRANSFORM, 4) &&
           VerifyField<FB_Utility::Matrix4x4>(verifier, VT_COMBINEDMATRIX, 4) &&
           VerifyField<int32_t>(verifier, VT_PARENTBONEINDEX, 4) &&
           VerifyOffset(verifier, VT_BONENAME) &&
           verifier.VerifyString(BoneName()) &&
           verifier.EndTable();
  }
};

struct BoneDataBuilder {
  typedef BoneData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_LocalTransform(const FB_Utility::Matrix4x4 *LocalTransform) {
    fbb_.AddStruct(BoneData::VT_LOCALTRANSFORM, LocalTransform);
  }
  void add_CombinedMatrix(const FB_Utility::Matrix4x4 *CombinedMatrix) {
    fbb_.AddStruct(BoneData::VT_COMBINEDMATRIX, CombinedMatrix);
  }
  void add_ParentBoneIndex(int32_t ParentBoneIndex) {
    fbb_.AddElement<int32_t>(BoneData::VT_PARENTBONEINDEX, ParentBoneIndex, 0);
  }
  void add_BoneName(::flatbuffers::Offset<::flatbuffers::String> BoneName) {
    fbb_.AddOffset(BoneData::VT_BONENAME, BoneName);
  }
  explicit BoneDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BoneData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BoneData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BoneData> CreateBoneData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const FB_Utility::Matrix4x4 *LocalTransform = nullptr,
    const FB_Utility::Matrix4x4 *CombinedMatrix = nullptr,
    int32_t ParentBoneIndex = 0,
    ::flatbuffers::Offset<::flatbuffers::String> BoneName = 0) {
  BoneDataBuilder builder_(_fbb);
  builder_.add_BoneName(BoneName);
  builder_.add_ParentBoneIndex(ParentBoneIndex);
  builder_.add_CombinedMatrix(CombinedMatrix);
  builder_.add_LocalTransform(LocalTransform);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BoneData> CreateBoneDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const FB_Utility::Matrix4x4 *LocalTransform = nullptr,
    const FB_Utility::Matrix4x4 *CombinedMatrix = nullptr,
    int32_t ParentBoneIndex = 0,
    const char *BoneName = nullptr) {
  auto BoneName__ = BoneName ? _fbb.CreateString(BoneName) : 0;
  return FB_Bone::CreateBoneData(
      _fbb,
      LocalTransform,
      CombinedMatrix,
      ParentBoneIndex,
      BoneName__);
}

inline const FB_Bone::BoneData *GetBoneData(const void *buf) {
  return ::flatbuffers::GetRoot<FB_Bone::BoneData>(buf);
}

inline const FB_Bone::BoneData *GetSizePrefixedBoneData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB_Bone::BoneData>(buf);
}

template <bool B = false>
inline bool VerifyBoneDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB_Bone::BoneData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedBoneDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB_Bone::BoneData>(nullptr);
}

inline void FinishBoneDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Bone::BoneData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBoneDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Bone::BoneData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FB_Bone

#endif  // FLATBUFFERS_GENERATED_FBBONE_FB_BONE_H_
