// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBMESHLOADER_FB_MESHLOADER_H_
#define FLATBUFFERS_GENERATED_FBMESHLOADER_FB_MESHLOADER_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "CommonStruct_generated.h"
#include "FB_Bone_generated.h"
#include "FB_Channel_generated.h"
#include "FB_DynamicMesh_generated.h"
#include "FB_StaticMesh_generated.h"

namespace FB_MeshLoader {

struct MeshLoader;
struct MeshLoaderBuilder;

struct MeshLoader FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshLoaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATICMESHLIST = 4,
    VT_DYNAMICMESHLIST = 6,
    VT_BONELIST = 8,
    VT_MAXVERTEXCOORD = 10,
    VT_MINVERTEXCOORD = 12
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshData>> *StaticMeshList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshData>> *>(VT_STATICMESHLIST);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshData>> *DynamicMeshList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshData>> *>(VT_DYNAMICMESHLIST);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FB_Bone::BoneData>> *BoneList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FB_Bone::BoneData>> *>(VT_BONELIST);
  }
  const FB_Utility::Vector3 *MaxVertexCoord() const {
    return GetStruct<const FB_Utility::Vector3 *>(VT_MAXVERTEXCOORD);
  }
  const FB_Utility::Vector3 *MinVertexCoord() const {
    return GetStruct<const FB_Utility::Vector3 *>(VT_MINVERTEXCOORD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STATICMESHLIST) &&
           verifier.VerifyVector(StaticMeshList()) &&
           verifier.VerifyVectorOfTables(StaticMeshList()) &&
           VerifyOffset(verifier, VT_DYNAMICMESHLIST) &&
           verifier.VerifyVector(DynamicMeshList()) &&
           verifier.VerifyVectorOfTables(DynamicMeshList()) &&
           VerifyOffset(verifier, VT_BONELIST) &&
           verifier.VerifyVector(BoneList()) &&
           verifier.VerifyVectorOfTables(BoneList()) &&
           VerifyField<FB_Utility::Vector3>(verifier, VT_MAXVERTEXCOORD, 4) &&
           VerifyField<FB_Utility::Vector3>(verifier, VT_MINVERTEXCOORD, 4) &&
           verifier.EndTable();
  }
};

struct MeshLoaderBuilder {
  typedef MeshLoader Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_StaticMeshList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshData>>> StaticMeshList) {
    fbb_.AddOffset(MeshLoader::VT_STATICMESHLIST, StaticMeshList);
  }
  void add_DynamicMeshList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshData>>> DynamicMeshList) {
    fbb_.AddOffset(MeshLoader::VT_DYNAMICMESHLIST, DynamicMeshList);
  }
  void add_BoneList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_Bone::BoneData>>> BoneList) {
    fbb_.AddOffset(MeshLoader::VT_BONELIST, BoneList);
  }
  void add_MaxVertexCoord(const FB_Utility::Vector3 *MaxVertexCoord) {
    fbb_.AddStruct(MeshLoader::VT_MAXVERTEXCOORD, MaxVertexCoord);
  }
  void add_MinVertexCoord(const FB_Utility::Vector3 *MinVertexCoord) {
    fbb_.AddStruct(MeshLoader::VT_MINVERTEXCOORD, MinVertexCoord);
  }
  explicit MeshLoaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshLoader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshLoader>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshLoader> CreateMeshLoader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshData>>> StaticMeshList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshData>>> DynamicMeshList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_Bone::BoneData>>> BoneList = 0,
    const FB_Utility::Vector3 *MaxVertexCoord = nullptr,
    const FB_Utility::Vector3 *MinVertexCoord = nullptr) {
  MeshLoaderBuilder builder_(_fbb);
  builder_.add_MinVertexCoord(MinVertexCoord);
  builder_.add_MaxVertexCoord(MaxVertexCoord);
  builder_.add_BoneList(BoneList);
  builder_.add_DynamicMeshList(DynamicMeshList);
  builder_.add_StaticMeshList(StaticMeshList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshLoader> CreateMeshLoaderDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshData>> *StaticMeshList = nullptr,
    const std::vector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshData>> *DynamicMeshList = nullptr,
    const std::vector<::flatbuffers::Offset<FB_Bone::BoneData>> *BoneList = nullptr,
    const FB_Utility::Vector3 *MaxVertexCoord = nullptr,
    const FB_Utility::Vector3 *MinVertexCoord = nullptr) {
  auto StaticMeshList__ = StaticMeshList ? _fbb.CreateVector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshData>>(*StaticMeshList) : 0;
  auto DynamicMeshList__ = DynamicMeshList ? _fbb.CreateVector<::flatbuffers::Offset<FB_DynamicMesh::DynamicMeshData>>(*DynamicMeshList) : 0;
  auto BoneList__ = BoneList ? _fbb.CreateVector<::flatbuffers::Offset<FB_Bone::BoneData>>(*BoneList) : 0;
  return FB_MeshLoader::CreateMeshLoader(
      _fbb,
      StaticMeshList__,
      DynamicMeshList__,
      BoneList__,
      MaxVertexCoord,
      MinVertexCoord);
}

inline const FB_MeshLoader::MeshLoader *GetMeshLoader(const void *buf) {
  return ::flatbuffers::GetRoot<FB_MeshLoader::MeshLoader>(buf);
}

inline const FB_MeshLoader::MeshLoader *GetSizePrefixedMeshLoader(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB_MeshLoader::MeshLoader>(buf);
}

template <bool B = false>
inline bool VerifyMeshLoaderBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB_MeshLoader::MeshLoader>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMeshLoaderBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB_MeshLoader::MeshLoader>(nullptr);
}

inline void FinishMeshLoaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_MeshLoader::MeshLoader> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMeshLoaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_MeshLoader::MeshLoader> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FB_MeshLoader

#endif  // FLATBUFFERS_GENERATED_FBMESHLOADER_FB_MESHLOADER_H_
