// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBMODEL_FB_MODEL_H_
#define FLATBUFFERS_GENERATED_FBMODEL_FB_MODEL_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "FB_Animator_generated.h"
#include "FB_MeshLoader_generated.h"

namespace FB_Model {

struct Model;
struct ModelBuilder;

struct Model FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODEL_ANIMATOR = 4,
    VT_MODEL_MESHLOADER = 6
  };
  const FB_Animator::Animator *Model_Animator() const {
    return GetPointer<const FB_Animator::Animator *>(VT_MODEL_ANIMATOR);
  }
  const FB_MeshLoader::MeshLoader *Model_MeshLoader() const {
    return GetPointer<const FB_MeshLoader::MeshLoader *>(VT_MODEL_MESHLOADER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MODEL_ANIMATOR) &&
           verifier.VerifyTable(Model_Animator()) &&
           VerifyOffset(verifier, VT_MODEL_MESHLOADER) &&
           verifier.VerifyTable(Model_MeshLoader()) &&
           verifier.EndTable();
  }
};

struct ModelBuilder {
  typedef Model Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_Model_Animator(::flatbuffers::Offset<FB_Animator::Animator> Model_Animator) {
    fbb_.AddOffset(Model::VT_MODEL_ANIMATOR, Model_Animator);
  }
  void add_Model_MeshLoader(::flatbuffers::Offset<FB_MeshLoader::MeshLoader> Model_MeshLoader) {
    fbb_.AddOffset(Model::VT_MODEL_MESHLOADER, Model_MeshLoader);
  }
  explicit ModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Model> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Model>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Model> CreateModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<FB_Animator::Animator> Model_Animator = 0,
    ::flatbuffers::Offset<FB_MeshLoader::MeshLoader> Model_MeshLoader = 0) {
  ModelBuilder builder_(_fbb);
  builder_.add_Model_MeshLoader(Model_MeshLoader);
  builder_.add_Model_Animator(Model_Animator);
  return builder_.Finish();
}

inline const FB_Model::Model *GetModel(const void *buf) {
  return ::flatbuffers::GetRoot<FB_Model::Model>(buf);
}

inline const FB_Model::Model *GetSizePrefixedModel(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB_Model::Model>(buf);
}

template <bool B = false>
inline bool VerifyModelBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB_Model::Model>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedModelBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB_Model::Model>(nullptr);
}

inline void FinishModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Model::Model> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_Model::Model> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FB_Model

#endif  // FLATBUFFERS_GENERATED_FBMODEL_FB_MODEL_H_
