// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBNAVIGATIONVERTEX_FB_NAVIGATIONVERTEX_H_
#define FLATBUFFERS_GENERATED_FBNAVIGATIONVERTEX_FB_NAVIGATIONVERTEX_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "CommonStruct_generated.h"

namespace FB_NavigationVertex {

struct FB_NavMeshCell;
struct FB_NavMeshCellBuilder;

struct FB_NavMesh;
struct FB_NavMeshBuilder;

struct FB_NavMeshCell FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FB_NavMeshCellBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CELLINDEX = 4,
    VT_CELLVERTEX = 6,
    VT_CELLNORMAL = 8,
    VT_ADJACENTCELL = 10,
    VT_CELLPLANE = 12
  };
  uint32_t CellIndex() const {
    return GetField<uint32_t>(VT_CELLINDEX, 0);
  }
  const ::flatbuffers::Vector<const FB_Utility::Vector3 *> *CellVertex() const {
    return GetPointer<const ::flatbuffers::Vector<const FB_Utility::Vector3 *> *>(VT_CELLVERTEX);
  }
  const ::flatbuffers::Vector<const FB_Utility::Vector3 *> *CellNormal() const {
    return GetPointer<const ::flatbuffers::Vector<const FB_Utility::Vector3 *> *>(VT_CELLNORMAL);
  }
  const ::flatbuffers::Vector<int32_t> *AdjacentCell() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_ADJACENTCELL);
  }
  const FB_Utility::Vector4 *CellPlane() const {
    return GetStruct<const FB_Utility::Vector4 *>(VT_CELLPLANE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CELLINDEX, 4) &&
           VerifyOffset(verifier, VT_CELLVERTEX) &&
           verifier.VerifyVector(CellVertex()) &&
           VerifyOffset(verifier, VT_CELLNORMAL) &&
           verifier.VerifyVector(CellNormal()) &&
           VerifyOffset(verifier, VT_ADJACENTCELL) &&
           verifier.VerifyVector(AdjacentCell()) &&
           VerifyField<FB_Utility::Vector4>(verifier, VT_CELLPLANE, 4) &&
           verifier.EndTable();
  }
};

struct FB_NavMeshCellBuilder {
  typedef FB_NavMeshCell Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_CellIndex(uint32_t CellIndex) {
    fbb_.AddElement<uint32_t>(FB_NavMeshCell::VT_CELLINDEX, CellIndex, 0);
  }
  void add_CellVertex(::flatbuffers::Offset<::flatbuffers::Vector<const FB_Utility::Vector3 *>> CellVertex) {
    fbb_.AddOffset(FB_NavMeshCell::VT_CELLVERTEX, CellVertex);
  }
  void add_CellNormal(::flatbuffers::Offset<::flatbuffers::Vector<const FB_Utility::Vector3 *>> CellNormal) {
    fbb_.AddOffset(FB_NavMeshCell::VT_CELLNORMAL, CellNormal);
  }
  void add_AdjacentCell(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> AdjacentCell) {
    fbb_.AddOffset(FB_NavMeshCell::VT_ADJACENTCELL, AdjacentCell);
  }
  void add_CellPlane(const FB_Utility::Vector4 *CellPlane) {
    fbb_.AddStruct(FB_NavMeshCell::VT_CELLPLANE, CellPlane);
  }
  explicit FB_NavMeshCellBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FB_NavMeshCell> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FB_NavMeshCell>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FB_NavMeshCell> CreateFB_NavMeshCell(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t CellIndex = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const FB_Utility::Vector3 *>> CellVertex = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const FB_Utility::Vector3 *>> CellNormal = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> AdjacentCell = 0,
    const FB_Utility::Vector4 *CellPlane = nullptr) {
  FB_NavMeshCellBuilder builder_(_fbb);
  builder_.add_CellPlane(CellPlane);
  builder_.add_AdjacentCell(AdjacentCell);
  builder_.add_CellNormal(CellNormal);
  builder_.add_CellVertex(CellVertex);
  builder_.add_CellIndex(CellIndex);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FB_NavMeshCell> CreateFB_NavMeshCellDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t CellIndex = 0,
    const std::vector<FB_Utility::Vector3> *CellVertex = nullptr,
    const std::vector<FB_Utility::Vector3> *CellNormal = nullptr,
    const std::vector<int32_t> *AdjacentCell = nullptr,
    const FB_Utility::Vector4 *CellPlane = nullptr) {
  auto CellVertex__ = CellVertex ? _fbb.CreateVectorOfStructs<FB_Utility::Vector3>(*CellVertex) : 0;
  auto CellNormal__ = CellNormal ? _fbb.CreateVectorOfStructs<FB_Utility::Vector3>(*CellNormal) : 0;
  auto AdjacentCell__ = AdjacentCell ? _fbb.CreateVector<int32_t>(*AdjacentCell) : 0;
  return FB_NavigationVertex::CreateFB_NavMeshCell(
      _fbb,
      CellIndex,
      CellVertex__,
      CellNormal__,
      AdjacentCell__,
      CellPlane);
}

struct FB_NavMesh FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FB_NavMeshBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAVMESHLIST = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<FB_NavigationVertex::FB_NavMeshCell>> *NavMeshList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FB_NavigationVertex::FB_NavMeshCell>> *>(VT_NAVMESHLIST);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAVMESHLIST) &&
           verifier.VerifyVector(NavMeshList()) &&
           verifier.VerifyVectorOfTables(NavMeshList()) &&
           verifier.EndTable();
  }
};

struct FB_NavMeshBuilder {
  typedef FB_NavMesh Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_NavMeshList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_NavigationVertex::FB_NavMeshCell>>> NavMeshList) {
    fbb_.AddOffset(FB_NavMesh::VT_NAVMESHLIST, NavMeshList);
  }
  explicit FB_NavMeshBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FB_NavMesh> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FB_NavMesh>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FB_NavMesh> CreateFB_NavMesh(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_NavigationVertex::FB_NavMeshCell>>> NavMeshList = 0) {
  FB_NavMeshBuilder builder_(_fbb);
  builder_.add_NavMeshList(NavMeshList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FB_NavMesh> CreateFB_NavMeshDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<FB_NavigationVertex::FB_NavMeshCell>> *NavMeshList = nullptr) {
  auto NavMeshList__ = NavMeshList ? _fbb.CreateVector<::flatbuffers::Offset<FB_NavigationVertex::FB_NavMeshCell>>(*NavMeshList) : 0;
  return FB_NavigationVertex::CreateFB_NavMesh(
      _fbb,
      NavMeshList__);
}

inline const FB_NavigationVertex::FB_NavMesh *GetFB_NavMesh(const void *buf) {
  return ::flatbuffers::GetRoot<FB_NavigationVertex::FB_NavMesh>(buf);
}

inline const FB_NavigationVertex::FB_NavMesh *GetSizePrefixedFB_NavMesh(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB_NavigationVertex::FB_NavMesh>(buf);
}

template <bool B = false>
inline bool VerifyFB_NavMeshBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB_NavigationVertex::FB_NavMesh>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedFB_NavMeshBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB_NavigationVertex::FB_NavMesh>(nullptr);
}

inline void FinishFB_NavMeshBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_NavigationVertex::FB_NavMesh> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFB_NavMeshBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_NavigationVertex::FB_NavMesh> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FB_NavigationVertex

#endif  // FLATBUFFERS_GENERATED_FBNAVIGATIONVERTEX_FB_NAVIGATIONVERTEX_H_
