// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBSTATICMESH_FB_STATICMESH_H_
#define FLATBUFFERS_GENERATED_FBSTATICMESH_FB_STATICMESH_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "CommonStruct_generated.h"

namespace FB_StaticMesh {

struct StaticMeshVertex;

struct StaticMeshTexture;
struct StaticMeshTextureBuilder;

struct StaticMeshData;
struct StaticMeshDataBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) StaticMeshVertex FLATBUFFERS_FINAL_CLASS {
 private:
  FB_Utility::Vector3 Position_;
  FB_Utility::Vector2 TexCoord_;
  FB_Utility::Vector3 Normal_;
  FB_Utility::Vector3 Tangent_;
  FB_Utility::Vector3 BiNormal_;

 public:
  StaticMeshVertex()
      : Position_(),
        TexCoord_(),
        Normal_(),
        Tangent_(),
        BiNormal_()
         {
  }
  StaticMeshVertex(const FB_Utility::Vector3 _Position, const FB_Utility::Vector2 _TexCoord, const FB_Utility::Vector3 _Normal, const FB_Utility::Vector3 _Tangent, const FB_Utility::Vector3 _BiNormal)
      : Position_(_Position),
      TexCoord_(_TexCoord),
        Normal_(_Normal),
        Tangent_(_Tangent),
        BiNormal_(_BiNormal)
         {
  }
  const FB_Utility::Vector3 &Position() const {
    return Position_;
  }
  const FB_Utility::Vector3 &Normal() const {
    return Normal_;
  }
  const FB_Utility::Vector3 &Tangent() const {
    return Tangent_;
  }
  const FB_Utility::Vector3 &BiNormal() const {
    return BiNormal_;
  }
  const FB_Utility::Vector2 &TexCoord() const {
    return TexCoord_;
  }
};
FLATBUFFERS_STRUCT_END(StaticMeshVertex, 56);

struct StaticMeshTexture FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StaticMeshTextureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEXTURETYPE = 4,
    VT_TEXTUREFILEPATH = 6
  };
  uint32_t TextureType() const {
    return GetField<uint32_t>(VT_TEXTURETYPE, 0);
  }
  const ::flatbuffers::String *TextureFilePath() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXTUREFILEPATH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TEXTURETYPE, 4) &&
           VerifyOffset(verifier, VT_TEXTUREFILEPATH) &&
           verifier.VerifyString(TextureFilePath()) &&
           verifier.EndTable();
  }
};

struct StaticMeshTextureBuilder {
  typedef StaticMeshTexture Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_TextureType(uint32_t TextureType) {
    fbb_.AddElement<uint32_t>(StaticMeshTexture::VT_TEXTURETYPE, TextureType, 0);
  }
  void add_TextureFilePath(::flatbuffers::Offset<::flatbuffers::String> TextureFilePath) {
    fbb_.AddOffset(StaticMeshTexture::VT_TEXTUREFILEPATH, TextureFilePath);
  }
  explicit StaticMeshTextureBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StaticMeshTexture> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StaticMeshTexture>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StaticMeshTexture> CreateStaticMeshTexture(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t TextureType = 0,
    ::flatbuffers::Offset<::flatbuffers::String> TextureFilePath = 0) {
  StaticMeshTextureBuilder builder_(_fbb);
  builder_.add_TextureFilePath(TextureFilePath);
  builder_.add_TextureType(TextureType);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StaticMeshTexture> CreateStaticMeshTextureDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t TextureType = 0,
    const char *TextureFilePath = nullptr) {
  auto TextureFilePath__ = TextureFilePath ? _fbb.CreateString(TextureFilePath) : 0;
  return FB_StaticMesh::CreateStaticMeshTexture(
      _fbb,
      TextureType,
      TextureFilePath__);
}

struct StaticMeshData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StaticMeshDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTEXLIST = 4,
    VT_INDEXLIST = 6,
    VT_TEXTURELIST = 8,
    VT_MAXCOORDVERTEX = 10,
    VT_MINCOORDVERTEX = 12,
    VT_SUBMESHLOCALMATRIX = 14
  };
  const ::flatbuffers::Vector<const FB_StaticMesh::StaticMeshVertex *> *VertexList() const {
    return GetPointer<const ::flatbuffers::Vector<const FB_StaticMesh::StaticMeshVertex *> *>(VT_VERTEXLIST);
  }
  const ::flatbuffers::Vector<uint32_t> *IndexList() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDEXLIST);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshTexture>> *TextureList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshTexture>> *>(VT_TEXTURELIST);
  }
  const FB_Utility::Vector3 *MaxCoordVertex() const {
    return GetStruct<const FB_Utility::Vector3 *>(VT_MAXCOORDVERTEX);
  }
  const FB_Utility::Vector3 *MinCoordVertex() const {
    return GetStruct<const FB_Utility::Vector3 *>(VT_MINCOORDVERTEX);
  }
  const FB_Utility::Matrix4x4 *SubMeshLocalMatrix() const {
    return GetStruct<const FB_Utility::Matrix4x4 *>(VT_SUBMESHLOCALMATRIX);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTEXLIST) &&
           verifier.VerifyVector(VertexList()) &&
           VerifyOffset(verifier, VT_INDEXLIST) &&
           verifier.VerifyVector(IndexList()) &&
           VerifyOffset(verifier, VT_TEXTURELIST) &&
           verifier.VerifyVector(TextureList()) &&
           verifier.VerifyVectorOfTables(TextureList()) &&
           VerifyField<FB_Utility::Vector3>(verifier, VT_MAXCOORDVERTEX, 4) &&
           VerifyField<FB_Utility::Vector3>(verifier, VT_MINCOORDVERTEX, 4) &&
           VerifyField<FB_Utility::Matrix4x4>(verifier, VT_SUBMESHLOCALMATRIX, 4) &&
           verifier.EndTable();
  }
};

struct StaticMeshDataBuilder {
  typedef StaticMeshData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_VertexList(::flatbuffers::Offset<::flatbuffers::Vector<const FB_StaticMesh::StaticMeshVertex *>> VertexList) {
    fbb_.AddOffset(StaticMeshData::VT_VERTEXLIST, VertexList);
  }
  void add_IndexList(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> IndexList) {
    fbb_.AddOffset(StaticMeshData::VT_INDEXLIST, IndexList);
  }
  void add_TextureList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshTexture>>> TextureList) {
    fbb_.AddOffset(StaticMeshData::VT_TEXTURELIST, TextureList);
  }
  void add_MaxCoordVertex(const FB_Utility::Vector3 *MaxCoordVertex) {
    fbb_.AddStruct(StaticMeshData::VT_MAXCOORDVERTEX, MaxCoordVertex);
  }
  void add_MinCoordVertex(const FB_Utility::Vector3 *MinCoordVertex) {
    fbb_.AddStruct(StaticMeshData::VT_MINCOORDVERTEX, MinCoordVertex);
  }
  void add_SubMeshLocalMatrix(const FB_Utility::Matrix4x4 *SubMeshLocalMatrix) {
    fbb_.AddStruct(StaticMeshData::VT_SUBMESHLOCALMATRIX, SubMeshLocalMatrix);
  }
  explicit StaticMeshDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StaticMeshData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StaticMeshData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StaticMeshData> CreateStaticMeshData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const FB_StaticMesh::StaticMeshVertex *>> VertexList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> IndexList = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshTexture>>> TextureList = 0,
    const FB_Utility::Vector3 *MaxCoordVertex = nullptr,
    const FB_Utility::Vector3 *MinCoordVertex = nullptr,
    const FB_Utility::Matrix4x4 *SubMeshLocalMatrix = nullptr) {
  StaticMeshDataBuilder builder_(_fbb);
  builder_.add_SubMeshLocalMatrix(SubMeshLocalMatrix);
  builder_.add_MinCoordVertex(MinCoordVertex);
  builder_.add_MaxCoordVertex(MaxCoordVertex);
  builder_.add_TextureList(TextureList);
  builder_.add_IndexList(IndexList);
  builder_.add_VertexList(VertexList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StaticMeshData> CreateStaticMeshDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<FB_StaticMesh::StaticMeshVertex> *VertexList = nullptr,
    const std::vector<uint32_t> *IndexList = nullptr,
    const std::vector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshTexture>> *TextureList = nullptr,
    const FB_Utility::Vector3 *MaxCoordVertex = nullptr,
    const FB_Utility::Vector3 *MinCoordVertex = nullptr,
    const FB_Utility::Matrix4x4 *SubMeshLocalMatrix = nullptr) {
  auto VertexList__ = VertexList ? _fbb.CreateVectorOfStructs<FB_StaticMesh::StaticMeshVertex>(*VertexList) : 0;
  auto IndexList__ = IndexList ? _fbb.CreateVector<uint32_t>(*IndexList) : 0;
  auto TextureList__ = TextureList ? _fbb.CreateVector<::flatbuffers::Offset<FB_StaticMesh::StaticMeshTexture>>(*TextureList) : 0;
  return FB_StaticMesh::CreateStaticMeshData(
      _fbb,
      VertexList__,
      IndexList__,
      TextureList__,
      MaxCoordVertex,
      MinCoordVertex,
      SubMeshLocalMatrix);
}

inline const FB_StaticMesh::StaticMeshData *GetStaticMeshData(const void *buf) {
  return ::flatbuffers::GetRoot<FB_StaticMesh::StaticMeshData>(buf);
}

inline const FB_StaticMesh::StaticMeshData *GetSizePrefixedStaticMeshData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FB_StaticMesh::StaticMeshData>(buf);
}

template <bool B = false>
inline bool VerifyStaticMeshDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<FB_StaticMesh::StaticMeshData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedStaticMeshDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<FB_StaticMesh::StaticMeshData>(nullptr);
}

inline void FinishStaticMeshDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_StaticMesh::StaticMeshData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStaticMeshDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FB_StaticMesh::StaticMeshData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FB_StaticMesh

#endif  // FLATBUFFERS_GENERATED_FBSTATICMESH_FB_STATICMESH_H_
