// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WORLDMAPSAVESCHEMAFILE_SAVEMAPDATA_H_
#define FLATBUFFERS_GENERATED_WORLDMAPSAVESCHEMAFILE_SAVEMAPDATA_H_

#include "FlatBuffer/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace SaveMapData {

struct Vector3;

struct MapObjectData;
struct MapObjectDataBuilder;

struct WorldMapData;
struct WorldMapDataBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 12);

struct MapObjectData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MapObjectDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ASSETPATH = 4,
    VT_OBJECTTAG = 6,
    VT_POSITION = 8,
    VT_ROTATION = 10,
    VT_SCALE = 12
  };
  const ::flatbuffers::String *assetpath() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ASSETPATH);
  }
  const ::flatbuffers::String *objecttag() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OBJECTTAG);
  }
  const SaveMapData::Vector3 *position() const {
    return GetStruct<const SaveMapData::Vector3 *>(VT_POSITION);
  }
  const SaveMapData::Vector3 *rotation() const {
    return GetStruct<const SaveMapData::Vector3 *>(VT_ROTATION);
  }
  const SaveMapData::Vector3 *scale() const {
    return GetStruct<const SaveMapData::Vector3 *>(VT_SCALE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ASSETPATH) &&
           verifier.VerifyString(assetpath()) &&
           VerifyOffset(verifier, VT_OBJECTTAG) &&
           verifier.VerifyString(objecttag()) &&
           VerifyField<SaveMapData::Vector3>(verifier, VT_POSITION, 4) &&
           VerifyField<SaveMapData::Vector3>(verifier, VT_ROTATION, 4) &&
           VerifyField<SaveMapData::Vector3>(verifier, VT_SCALE, 4) &&
           verifier.EndTable();
  }
};

struct MapObjectDataBuilder {
  typedef MapObjectData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_assetpath(::flatbuffers::Offset<::flatbuffers::String> assetpath) {
    fbb_.AddOffset(MapObjectData::VT_ASSETPATH, assetpath);
  }
  void add_objecttag(::flatbuffers::Offset<::flatbuffers::String> objecttag) {
    fbb_.AddOffset(MapObjectData::VT_OBJECTTAG, objecttag);
  }
  void add_position(const SaveMapData::Vector3 *position) {
    fbb_.AddStruct(MapObjectData::VT_POSITION, position);
  }
  void add_rotation(const SaveMapData::Vector3 *rotation) {
    fbb_.AddStruct(MapObjectData::VT_ROTATION, rotation);
  }
  void add_scale(const SaveMapData::Vector3 *scale) {
    fbb_.AddStruct(MapObjectData::VT_SCALE, scale);
  }
  explicit MapObjectDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MapObjectData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MapObjectData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MapObjectData> CreateMapObjectData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> assetpath = 0,
    ::flatbuffers::Offset<::flatbuffers::String> objecttag = 0,
    const SaveMapData::Vector3 *position = nullptr,
    const SaveMapData::Vector3 *rotation = nullptr,
    const SaveMapData::Vector3 *scale = nullptr) {
  MapObjectDataBuilder builder_(_fbb);
  builder_.add_scale(scale);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  builder_.add_objecttag(objecttag);
  builder_.add_assetpath(assetpath);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MapObjectData> CreateMapObjectDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *assetpath = nullptr,
    const char *objecttag = nullptr,
    const SaveMapData::Vector3 *position = nullptr,
    const SaveMapData::Vector3 *rotation = nullptr,
    const SaveMapData::Vector3 *scale = nullptr) {
  auto assetpath__ = assetpath ? _fbb.CreateString(assetpath) : 0;
  auto objecttag__ = objecttag ? _fbb.CreateString(objecttag) : 0;
  return SaveMapData::CreateMapObjectData(
      _fbb,
      assetpath__,
      objecttag__,
      position,
      rotation,
      scale);
}

struct WorldMapData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WorldMapDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORLDMAPTAG = 4,
    VT_OBJECTLIST = 6
  };
  const ::flatbuffers::String *worldmaptag() const {
    return GetPointer<const ::flatbuffers::String *>(VT_WORLDMAPTAG);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<SaveMapData::MapObjectData>> *objectlist() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SaveMapData::MapObjectData>> *>(VT_OBJECTLIST);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_WORLDMAPTAG) &&
           verifier.VerifyString(worldmaptag()) &&
           VerifyOffset(verifier, VT_OBJECTLIST) &&
           verifier.VerifyVector(objectlist()) &&
           verifier.VerifyVectorOfTables(objectlist()) &&
           verifier.EndTable();
  }
};

struct WorldMapDataBuilder {
  typedef WorldMapData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_worldmaptag(::flatbuffers::Offset<::flatbuffers::String> worldmaptag) {
    fbb_.AddOffset(WorldMapData::VT_WORLDMAPTAG, worldmaptag);
  }
  void add_objectlist(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SaveMapData::MapObjectData>>> objectlist) {
    fbb_.AddOffset(WorldMapData::VT_OBJECTLIST, objectlist);
  }
  explicit WorldMapDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WorldMapData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WorldMapData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WorldMapData> CreateWorldMapData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> worldmaptag = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SaveMapData::MapObjectData>>> objectlist = 0) {
  WorldMapDataBuilder builder_(_fbb);
  builder_.add_objectlist(objectlist);
  builder_.add_worldmaptag(worldmaptag);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WorldMapData> CreateWorldMapDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *worldmaptag = nullptr,
    const std::vector<::flatbuffers::Offset<SaveMapData::MapObjectData>> *objectlist = nullptr) {
  auto worldmaptag__ = worldmaptag ? _fbb.CreateString(worldmaptag) : 0;
  auto objectlist__ = objectlist ? _fbb.CreateVector<::flatbuffers::Offset<SaveMapData::MapObjectData>>(*objectlist) : 0;
  return SaveMapData::CreateWorldMapData(
      _fbb,
      worldmaptag__,
      objectlist__);
}

inline const SaveMapData::WorldMapData *GetWorldMapData(const void *buf) {
  return ::flatbuffers::GetRoot<SaveMapData::WorldMapData>(buf);
}

inline const SaveMapData::WorldMapData *GetSizePrefixedWorldMapData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SaveMapData::WorldMapData>(buf);
}

template <bool B = false>
inline bool VerifyWorldMapDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<SaveMapData::WorldMapData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedWorldMapDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<SaveMapData::WorldMapData>(nullptr);
}

inline void FinishWorldMapDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SaveMapData::WorldMapData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedWorldMapDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SaveMapData::WorldMapData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace SaveMapData

#endif  // FLATBUFFERS_GENERATED_WORLDMAPSAVESCHEMAFILE_SAVEMAPDATA_H_
